package com.project.performanceTrack.enums;

public enum NotificationType {
    ACCOUNT_CREATED,
    GOAL_SUBMITTED,
    GOAL_APPROVED,
    GOAL_CHANGE_REQUESTED,
    GOAL_RESUBMITTED,
    GOAL_COMPLETION_SUBMITTED,
    GOAL_COMPLETION_APPROVED,
    ADDITIONAL_EVIDENCE_REQUIRED,
    REVIEW_REMINDER,
    SELF_ASSESSMENT_SUBMITTED,
    PERFORMANCE_REVIEW_COMPLETED,
    REVIEW_ACKNOWLEDGED
}